version: "3.7"
services:
  library-api:
    image: library:0.0.1-SNAPSHOT
    ports:
      - "${HOST_PORT}:8080"
    networks:
      - connector
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  connector:
    name: connector